import { Geist, Geist_Mono, Lalezar } from "next/font/google";
import "./globals.css";

const geistLalezar = Lalezar({
  variable: "--font-geist-lalezar",
  weight: "400",
  subsets: ["arabic"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${geistLalezar.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
